// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ufoousnidesoulsaqdes.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmb291c25pZGVzb3Vsc2FxZGVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NTYzMTIsImV4cCI6MjA2MjAzMjMxMn0.mAw0XVHXJvQy6I4z12LXE_MRFP5RP6dDY92ZdP_WLW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);